with 
source as (
    select
        rider_id::int as rider_id,
        name::varchar as rider,
        club__id::int as club_id,
        club__name::varchar as club,
        gender::varchar as gender,
        country::varchar as country,
        age::varchar as age_category,
        height::int as height_cm,
        coalesce(weight__v_double::float, weight::float) as weight_kg,

        zp_ftp::int as ftp,
        power__cp::float as critical_power,
        coalesce(power__awc__v_double::float, power__awc::float) as work_capacity,
        power__compound_score::float as compound_power_score,
        power__wkg5::float as wkg_5,
        power__wkg15::float as wkg_15,
        power__wkg30::float as wkg_30,
        power__wkg60::float as wkg_60,
        power__wkg120::float as wkg_120,
        power__wkg300::float as wkg_300,
        power__wkg1200::float as wkg_1200,
        power__w5::int as watts_5,
        power__w15::int as watts_15,
        power__w30::int as watts_30,
        power__w60::int as watts_60,
        power__w120::int as watts_120,
        power__w300::int as watts_300,
        power__w1200::int as watts_1200,

        race__finishes::int as race_finishes,
        race__dnfs::int as race_dnfs,
        race__wins::int as race_wins,
        race__podiums::int as race_podiums,

        zp_category::varchar as zwift_category,
        zrs__score::float as zwift_racing_score,
        zrs__event_time::int as zwift_racing_score_timestamp,
        race__current__rating::float as velo,
        race__current__mixed__number::int as velo_category,
        race__max30__rating::float as velo_30day,
        race__max30__mixed__number::int as velo_30day_category,
        race__max90__rating::float as velo_90day,
        race__max90__mixed__number::int as velo_90day_category,
        velo__race::float as velo2_race,
        velo__time_trial::float as velo2_timetrial,
        coalesce(velo__factors__endurance__v_double::float, velo__factors__endurance::float) as velo_factor_endurance,
        coalesce(velo__factors__pursuit__v_double::float, velo__factors__pursuit::float) as velo_factor_pursuit,
        coalesce(velo__factors__sprint__v_double::float, velo__factors__sprint::float) as velo_factor_sprint,
        velo__factors__punch::float as velo_factor_punch,
        coalesce(velo__factors__climb__v_double::float, velo__factors__climb::float) as velo_factor_climb,
        coalesce(velo__factors__time_trial__v_double::float, velo__factors__time_trial::float) as velo_factor_time_trial,

        phenotype__value::varchar as phenotype,
        phenotype__scores__sprinter::float as phenotype_sprinter,
        phenotype__scores__puncheur::float as phenotype_puncheur,
        phenotype__scores__pursuiter::float as phenotype_pursuiter,
        phenotype__scores__climber::float as phenotype_climber,
        phenotype__scores__tt::float as phenotype_timetrialist,
        handicaps__profile__flat::float as handicap_flat,
        handicaps__profile__rolling::float as handicap_rolling,
        handicaps__profile__hilly::float as handicap_hilly,
        handicaps__profile__mountainous::float as handicap_mountainous,

        _dlt_load_id::float as _dlt_load_id,
        _dlt_id::varchar as _dlt_id,

        -- coalesce(velo__skill__endurance__v_double, velo__skill__endurance),
        -- coalesce(velo__skill__pursuit__v_double, velo__skill__pursuit),
        -- coalesce(velo__skill__sprint__v_double,velo__skill__sprint),
        -- coalesce(velo__skill__punch__v_double, velo__skill__punch),
        -- coalesce(velo__skill__climb__v_double, velo__skill__climb),
        -- coalesce(velo__skill__time_trial__v_double, velo__skill__time_trial),
        -- seed__race,
        -- seed__time_trial,
        -- seed__factors__endurance,
        -- seed__factors__pursuit,
        -- coalesce(seed__factors__sprint__v_double, seed__factors__sprint),
        -- seed__factors__punch,
        -- coalesce(seed__factors__climb__v_double, seed__factors__climb),
        -- seed__factors__time_trial,
        -- phenotype__bias,
        -- race__max90__date,
        -- race__max90__expires,
        -- race__max90__mixed__category,
        -- race__max30__date,
        -- race__max30__expires,
        -- race__max30__mixed__category,
        -- race__current__date,
        -- race__current__mixed__category,
        -- race__last__rating,
        -- race__last__date,
        -- race__last__mixed__category,
        -- race__last__mixed__number,
        -- weight_changed_at,
        -- race__current__womens__category,
        -- race__current__womens__number,
        
    from {{ source("raw_zwift_racing", "riders") }}   
)

select *
from source